# Generated by Django 4.2.23 on 2025-09-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentallisting',
            old_name='availability_date',
            new_name='availability_dates',
        ),
    ]
